### ISSUE TITLE
Build the Syntax Tree from the UI Code Editor for the Programming Framework

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#116]
## Description

The Programming Framework needs to build the syntax tree of the instructions before it can execute them. Build the syntax tree for the Programming Framework from the instructions available in the Code Editor.

There are two internal functions: `checkValidity` and `transpile` inside the top level function `buildProgram` in [`src/components/editor/core/index.ts`](https://github.com/sugarlabs/musicblocks-v4/blob/develop/src/components/editor/core/index.ts). The `checkValidity` function is supposed to check for syntax validity. The `transpile` function is supposed to convert the editor syntax to `ITreeSnapshotInput` format. There exists some rudimentary implementation of these which need to be improved upon.

The editor syntax should be as:

```text
instruction-1 arg-1:value arg-2:value
  nested-instruction-1 arg-1:value
  nested-instruction-2
```

Here's an example:

```text
set-thickness value:1
set-color value:5
repeat times:6
  move-forward steps:100
  turn-right angle:60
set-color value:9
repeat times:6
  move-forward steps:100
  turn-left angle:60
```

## Objectives

- [ ] Validate the syntax in the Code Editor
- [ ] Build the Syntax Tree for the Programming Framework

Ignore token validation (e.g., whether `move-forward` is a valid instruction and `steps` is a valid argument to it) for now. Validation should be simpler; building the snapshot is a little challenging.

<hr />

**Please make separate Pull Requests.**

**Comment by impAkshat** [comment]
For the **Validate the syntax in the Code Editor** objective -

Is the requirement is to change `checkValidity` function and check whether the `code` in the editor is in 
```
instruction-1 arg-1:value arg-2:value
  nested-instruction-1 arg-1:value
  nested-instruction-2
```
this kind of format or not?

**Comment by meganindya** [comment]
yes

**Comment by impAkshat** [comment]
Should it validate the indentations also ?

eg - 
For this code

```
instruction-1 arg-1:value arg-2:value
    nested-instruction-1 arg-1:value
  nested-instruction-2
```

function will return false.

**Comment by meganindya** [comment]
do it in two stages.

1. Instruction format
2. Nesting

**Comment by meganindya** [comment]
Nesting will be a little challenging because you'll require to track the current nest levels per instruction

**Comment by impAkshat** [comment]
If there is an expression in argument value, what will be its syntax will it be

`move-forward steps:100/4`

(without spaces)

or something like

`move-forward steps:/:100 4`

**Comment by meganindya** [comment]
just ignore that case for now
