### ISSUE TITLE
Painter: Add wrappers around core graphics functions (around p5.js)

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#125]
## Description

The Painter component is responsible for drawing artworks on the canvas. Add core functions wrapping functions of p5.js, in [painter/sketchP5.ts](https://github.com/sugarlabs/musicblocks-v4/blob/painter/src/components/painter/sketchP5.ts). Add dummy calls in [painter/painter.ts](https://github.com/sugarlabs/musicblocks-v4/blob/painter/src/components/painter/painter.ts) to test them.

Use [p5.js reference](https://p5js.org/reference/) as reference.

## Objectives

- [x] set background color
- [x] set thickness
- [x] set color
- [x] draw line
- [x] clear canvas
- [x] set fill on
- [x] set fill off
- [x] draw point
- [x] draw arc
- [x] draw bezier

Branch out of [painter](https://github.com/sugarlabs/musicblocks-v4/tree/painter) and target your PRs at the same.

**Comment by ishubham21** [comment]
Hi @meganindya. I wanted to work on this, how about I complete 'draw point, draw arc, and draw bezier'?

**Comment by meganindya** [comment]
Go ahead.

**Comment by ishubham21** [comment]
@meganindya functions like arc and bezier accept more than 5/6 params. Is it okay to have a warning that says "The line has a length of 120. Maximum allowed is 100". If not, can I make a single object to be accepted as a parameter?

**Comment by meganindya** [comment]
Why do you need to go beyond 100 characters per line?

**Comment by ishubham21** [comment]
> Why do you need to go beyond 100 characters per line?

Because functions like arc takes 5 compulsary parameters, so the function definition looks something like -
function drawArc(x: Number, y: Number, w: Number, h: Number, start: Number, end: Number, mode: p5.ARC_MODE): void {}

**Comment by meganindya** [comment]
you don't need the `mode`

```ts
export function drawArc(x: number, y: number, w: number, h: number, start: number, end: number) {
   ...
}
```

**Comment by meganindya** [comment]
when things don't fit in one line, you can always do

```typescript
export function drawArc(
    x: number,
    y: number,
    w: number,
    h: number,
    start: number,
    end: number,
) {
   ...
}
```

**Comment by ishubham21** [comment]
> when things don't fit in one line, you can always do
> 
> ```ts
> export function drawArc(
>     x: number,
>     y: number,
>     w: number,
>     h: number,
>     start: number,
>     end: number,
> ) {
>    ...
> }
> ```

Thank you @meganindya. Made a PR - https://github.com/sugarlabs/musicblocks-v4/pull/127, please review it.
