### ISSUE TITLE
Replace react-scripts with explicit Webpack configurations

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#129]
## Description

A frontend framework comes with some good features like independent components, virtual DOM, and component states. **React** on top of that is technically "_a JavaScript library for building user interfaces_" and their website adds "_use as little or as much React as you need_", which makes it appealing to our use case. However, it is important to note that Music Blocks (v4) will not be a React application in strict terms. We might want to leverage some of its features later on, but it isn't a necessity.

Music Blocks by itself doesn't have too many complex DOM components with inter-dependencies. Most of the complexity of the application is in the background components which are simply plain JavaScript (TypeScript). Therefore, it is imperative not to rely on the `create-react-app` template, or more specifically `react-scripts`. It is a good starter, however, it packs too many things than what we require, and abstracts the configurations entirely.

The objective is to explicitly configure the project with **Webpack** and **WebpackDevServer** (for development-time hot reloading) and remove dependency on `react-scripts`.

## Expectations

- [x] Configure `webpack` (preferably v5), `webpack-dev-server`, and `webpack-cli`.
- [x] Create a basic configurations file (`webpack.config.common.js`) for both development and production.
- [x] Use `webpack-merge` to inherit the basic configurations and add on top of that in separate files for development (`webpack.config.dev.js`) and production (`webpack.config.prod.js`).
- [x] Replicate basic `react-scripts` hot-reloading behaviour (including `eslint` checks).
- [x] Add fast build configurations for development.
- [x] Add optimised build configurations for production.
- [ ] Add scripts to overwrite `webpack` logs with more select (and readable) logs.

<hr/>

**This is an open-ended issue. Feel free to discuss untouched points in the comments.**

**Comment by ishubham21** [comment]
Do we need html-webpack-plugin to work alongside webpack-dev-server? - https://github.com/merkle-open/webpack-config-plugins/blob/master/README.md#zero-config-webpack-dev-server-example

**Comment by meganindya** [comment]
Yes. And `MiniCssExtractPlugin` too. And we'll require all sorts of loaders.

**Comment by ishubham21** [comment]
> Yes. And `MiniCssExtractPlugin` too. And we'll require all sorts of loaders.

I'm not sure if I'd be able to do it or not, but I'm on it.

**Comment by meganindya** [comment]
Please go piece by piece. This one will take some time as a whole. Try to start with a basic configuration for a project with HTML templates, SCSS, TypeScript, images (PNG, JPG, JPEG, GIF, SVG), and a babel loader for target transpiling.

**Comment by meganindya** [comment]
Thanks for your interest. I don't have the bandwidth right now to go all in all by myself. We can work together on this.

**Comment by ishubham21** [comment]
Hi @meganindya. I did make some progress, deconstructed one of my react applications with Webpack5 and Babel7, however, I ran into a small problem - I now have to manually import react at the top of each component. Is there any way around this?

**Comment by meganindya** [comment]
I remember doing this. something with some babel presets. That supports react JSX without compiling.

**Comment by meganindya** [comment]
See https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

**Comment by ishubham21** [comment]
![Screenshot from 2022-01-30 12-49-18](https://user-images.githubusercontent.com/34435822/151690579-42c1681e-8b9c-414a-9f53-89e9ab4a2f31.png)
I am done with deconstructing musicblocks with webpack-5 and babel-8, but here's an issue that I ran into. I am stuck since clear() expects no parameter. 

Commenting the line -
`sketch.clear()` eliminates all the errors. What do you suggest in this case?

**Comment by ishubham21** [comment]
Made a PR - https://github.com/sugarlabs/musicblocks-v4/pull/132. Please suggest the changes, also how do I get past the failed lint checks? Do I need to update eslint configurations?

**Comment by meganindya** [comment]
Commenting out code isn't a fix. Especially in this case. I'll look into it.

**Comment by ishubham21** [comment]
> Commenting out code isn't a fix. Especially in this case. I'll look into it.

I understand but I was not able to find a fix. 

Meanwhile you review my changes, can you please guide me to the projects that are looking for contributions?

**Comment by ishubham21** [comment]
> projects?

Potential repositories under sugarlabs that are currently expanding and looking for more contributions.

**Comment by meganindya** [comment]
I only manage Music Blocks. You can join the [sugar-devel mailing list](http://lists.sugarlabs.org/listinfo/sugar-devel) for queries and discussions on Sugar Labs wide topics. We have a [Music Blocks IRC channel](https://matrix.to/#/#musicblocksdev:matrix.org) for general discussions for Music Blocks.

**Comment by ishubham21** [comment]
> I only manage Music Blocks. You can join the [sugar-devel mailing list](http://lists.sugarlabs.org/listinfo/sugar-devel) for queries and discussions on Sugar Labs wide topics. We have a [Music Blocks IRC channel](https://matrix.to/#/#musicblocksdev:matrix.org) for general discussions for Music Blocks.

Got it. Thank you.

**Comment by meganindya** [comment]
Completed (except last item) during GSoC 2022 in #206.

Issue #220 created for last item.
