### ISSUE TITLE
Painter: Add new Syntax Element classes

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#137]
## Description

Create new Syntax Elements to add new instructions to the Painter component's [`src/components/painter/painter.ts`](https://github.com/sugarlabs/musicblocks-v4/blob/develop/src/components/painter/painter.ts) module. See existing Syntax Element classes for help. Thereafter, register the new classes in [`src/components/painter/index.ts`](https://github.com/sugarlabs/musicblocks-v4/blob/develop/src/components/painter/index.ts). To debug, try out the added instructions in the _Editor_.

## Objectives

Create following Syntax Element classes:

- [x] `ElementSetXY`: Updates sprite position to (`x`, `y`)
  - name: `set-xy`
  - label: `set-xy`
  - args:
    - `x: number`
    - `y: number`
- [x] `ElementSetHeading`: Updates sprite heading to `angle` degrees
  - name: `set-heading`
  - label: `set-heading`
  - args:
    - `angle: number`
- [x] `ElementDrawArc`: Draws an arc with `radius` and `angle`
  - name: `draw-arc`
  - label: `draw-arc`
  - args:
    - `radius: number`
    - `angle: number`
- [x] `ElementClear`: Clears the canvas
  - name: `clear`
  - label: `clear`
- [x] `ElementPenUp`: Stops canvas drawing, only moves sprites on _draw_ instructions
  - name: `pen-up`
  - label: `pen-up`
- [x] `ElementPenDown`: Enables canvas drawing
  - name: `pen-down`
  - label: `pen-down`
- [x] `ElementSetBackground`: Sets the background color (refer to `ElementSetColor` for colour list)
  - name: `set-background`
  - label: `set-background`
  - args:
    - `color: number`

<hr />

**This issue can be completed through multiple PRs. Make sure to separate out commits per class.**

**Comment by knmn2000** [comment]
I'd like to take this issue up. I'll make a PR for it asap.

**Comment by VaibhavSharma-47** [comment]
Apologies I started working on the issue without adding a comment here. Added ElementSetXY

**Comment by meganindya** [comment]
You don't need to add a comment :p

**Comment by saieswar13** [comment]
Can I work on this issue?

**Comment by d-e-v-esh** [comment]
I have started working on `ElementDrawArc`.

**Comment by d-e-v-esh** [comment]
@Udai1931 This is really good. 👍

**Comment by Udai1931** [comment]
Thanks, @d-e-v-esh.✌🏻

**Comment by d-e-v-esh** [comment]
I think there could be another argument added to `ElementDrawArc` that will describe if it wants to make the arc in the clockwise direction or counter-clockwise, We can just use keywords `right` or `left` to describe that direction before radius and angle like:
```js
draw-arc direction:right radius:200 angle:20
```
Is that a good idea?

**Comment by walterbender** [comment]
It could alos be done by simply changing the sign of the angle.

**Comment by meganindya** [comment]
I made some design choices. By cartesian grid conventions, radially anticlockwise angle is positive and clockwise in negative. Also, 0 degrees lie along the positive x axis.

However, since the sprite faces upward in Music Blocks initially, I chose to put 0 degrees along the positive y axis. Angle sign conventions remain the same. So, by that convention, turning left is a positive angle change and turning right is a negative angle change.

If we follow that, specifying the start and end angles should be enough to understand the direction (right or left) of the arc's curvature.

**Comment by Udai1931** [comment]
Yes got it. I have made the required changes. Right now, there is a dir variable which has value 1/-1 depending upon -ve/+ve value of angle provided and this will increment/decrement the sprite heading accordingly.
Also I have directly incremented/decremented sprite heading so there is no need for 90 degree correction in this case.

**Comment by meganindya** [comment]
I wouldn't want to do that. I'd like to explicitly maintain the delta because the sprite by convention has 0 degrees upward but sketch has 0 degrees rightward. I'll take a look.
