### ISSUE TITLE
Editor: Add line numbers

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#154]
## Description

The objective of this issue is to add line numbers to the code-box of the editor component. The code-box is an `HTMLTextAreaElement`.

- Wrap `textarea#"editor-codebox"` in another `div` with `id="editor-codebox-wrapper"`.
- Add a `p#editor-codebox-line-numbers` inside `editor-codebox-wrapper` (line numbers go inside this).
- Make applicable SCSS changes.
- Add event listener so that when the `value` of `editor-codebox` changes, line numbers update accordingly.

**Comment by sagnik2001** [comment]
Can I work on this issue?

**Comment by rksingh2001** [comment]
Can I take up this issue @meganindya

**Comment by meganindya** [comment]
Current editor will be replaced. Please look out for new issues. Thanks for taking interest.
