### ISSUE TITLE
Editor: Generate API of valid instructions

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#155]
## Description

The editor component transpiles code into a snapshot for the `generateFromSnapshot` function of the Programming Framework's Syntax Tree component. Syntax tree will only be generated from registered elements. The objective is to add a feature so that the editor displays the valid instructions with their signatures.

**Comment by saieswar13** [comment]
could you please assign this issue to me?

**Comment by d-e-v-esh** [comment]
@meganindya What is it supposed to look like? 

Are we supposed to create a nice-looking list of commands that the app accepts to show the user or is it supposed to work like IntelliSense where it'll show up as the code is being written?

**Comment by meganindya** [comment]
I'm working on this.
