### ISSUE TITLE
Menus Framework

### ISSUE THREAD

**Issue by daksh4469** [sugarlabs/musicblocks-v4#56]
# Introduction
The Menu contains various buttons with unique functionalities for a project. The objectives of various buttons are as follows:
- Help: To display the about page
- Play Button: To run the current project
- Play Step by Step Button: To run the project step by step
- Play Slowly: To run the project in slow mode
- Stop: To stop the running project
- New Project: To create a new project from scratch
- Save: To save the project in different formats
- Load: To load a local project from a file in Music Blocks
- Merge: To merge a project with the current project
- Restore: To restore the most recently deleted block/block-stack
- Language Selection: To select the desired language
- Enable Horizontal Scroll: To enable horizontal scroll for the canvas
- Turtle Wrap: To enable/disable turtle wrap

# Architecture

MVC(Model View Controller) Architecture of the Menu Component.

![MVC_adobespark](https://user-images.githubusercontent.com/60084414/121290551-741c5c80-c904-11eb-81c8-88fe1bd477ec.png)

## Model
Corresponds to various data and states required for the functionalities of the Menus in Music Blocks v4.

#### Variables:
- `language`(maintains the language opted by the user)
- `mode` (advanced/beginner)
- `saveSVG`(the feature to save artwork as SVG gets disabled in case there is no artwork present)
- `savePNG`(the feature to save artwork as PNG gets disabled in case there is no artwork present)
- `auxMenuOpen`(determines if the auxiliary menu is open or closed)
- List of items in the required dropdowns.

## Controller
It is the interface between the Model and the View and processes the incoming requests by manipulating the data model and rendering the results in the view component. The controller communicates with the monitor which in turn can interact with the controllers of every component in the architecture.

#### Methods:
- `showAboutPage()`: to display the about page of Music Blocks v4
- `playFast()`: on clicking the Play button
- `playStepByStep()`: on clicking the Play Step by Step button
- `playSlow()`: on clicking the Play Slowly button
- `doHardStop()`: on clicking the Stop button
- `newProject()`/`afterDelete()`: on clicking the New Project Icon
- `showHideAuxMenu()`: to show/hide the auxiliary menu
- `restoreTrash()`: to restore the most recently deleted block/block-stack
- `switchMode()`: to switch modes between beginner and advanced
- `doLoad()`: to load a file in Music Blocks v4
- `doMergeLoad()`: to merge with the current project
- `setScroller()`: to enable horizontal scroll
- Methods related to Plugins and displaying the Statistics and JSEditor window.
 
#### Methods:
- `allClear()`: to clear the canvas
- `textMsg()`: to display information
- `refreshCanvas()`: to update the canvas elements
- `hideBlocks()`: to hide the blocks while a project is running
- `runLogoCommands()`: to run the blocks in the project(currently in [logo.js](https://github.com/sugarlabs/musicblocks/blob/master/js/logo.js) file)
- `stopTurtles()`: to stop the turtles when the stop button is clicked
- `sendAllToTrash()`: to send all the blocks to trash
- `loadNewBlocks()`: to load new blocks
- `step()`: to execute one step from each turtle while executing logo commands

#### Variables:
- `turtlesRunning`: to determine if the project is already running or not

**Comment by meganindya** [comment]
Good progress. But I think there are a few changes. Try listing all the functionalities first (in textual english). Then it'll be easier for you to identify.

**Comment by meganindya** [comment]
I think we want to include the canvas specific buttons into the menu itself. 
things like zoom in/out, background, show/hide blocks etc.

**Comment by meganindya** [comment]
Please make a checklist according to the expected structure (and update the data and action members according to our discussions, e.g. no modes).

**Comment by meganindya** [comment]
completed in #95.
