### ISSUE TITLE
Palette Framework

### ISSUE THREAD

**Issue by joykirat18** [sugarlabs/musicblocks-v4#57]
# Objective 
Redesign the palette section of MusicBlock, and implement it in react. The palette section implements the feature of the low shelf and high shelf blocks so that we can remove the feature of beginner and advance mode in musicBlock v4.
The workflow is divided into 3 main objectives.

## Objective - 1
Implement the palette main component which handles the visibility and position of the entire palette and renders the selector buttons along with their categories currently music, logic, and art.

## Objective - 2
Handle the visibility of blocks corresponding to each selector buttons, and also the interaction of the blocks ( dragging and dropping them on canvas). This sub-component will also show the low shelf blocks and the high shelf (which are rarely used) and will be put in a different section.

## Objective - 3 
Implement a drop-down feature for high shelf blocks. At the end of the list of blocks corresponding to each selector buttons, there will be another subCategory. On clicking this subcategory another dropdown will be opened which will contain more high shelf blocks.

## 
According to the objectives, the palette section will be divided into 3 components :
1. Palette
2. BlockPalette
3. DropDownPalette

All the three will be divided into their own respective model, view and controller. 
Palette : Render the categories and their corresponding selector buttons.
BlockPalette : Render blocks linked to each button and implement interaction of blocks.
DropDownPalette : Create a subcategory within the block list, which contains additional blocks.

![Screenshot 2021-06-10 at 3 24 18 PM](https://user-images.githubusercontent.com/66181127/121504835-f0479a80-c9ff-11eb-87b3-7185559ba38b.png)

## Model:
Stores all the state and data required by the components

## Controller:
The controller will fetch the data from the model and render the results using the View. It also communicates with the monitor of MusicBlock, which provides and fetches data to other controllers.

### PaletteModel
 
`sectionList = []` (store the different section palettes are divide, currently music, logic and art/ fetched from other files)
`defaultSection` (The section shown when music block is first opened)
`activeSection` (The section currently selected)
`buttonList = []` (list of buttons in each section, fetched from other files)
`buttonSelected` (The button selected in a section)

### PaletteController

`makePaletteIcons` (render the icons of the section)
`makeSections` (render the view of the sections)
`onClickSection` (Will call makeButtons to render the buttons)
`makeButtons` (render the buttons in each section)
`onClickButton` (triggers the makeBlocks function when a button is clicked)
`makeBlocks` ( call the blockPaletteController which will render the blocks corresponding to each button)
 

### BlockPaletteModel

`selectedButton` (store the name of the button clicked)
`paletteList = []` (list of palettes corresponding to each button)
`MenuHidden = true/false` (stores whether the menu storing the blocks is shown or hidden)
`setX` (the x coordinate of the block when it is dragged to the canvas)
`setY` (the y coordinate of the block when it is dragged to the canvas)

### BlockPaletteController

`showMenu` (set the menuHidden value to false and display the menus that will contain the blocks)
`hideMenu` (set the menuHidden value to true)
`renderBlocks` (this function will call the monitor to return the svgs of the blocks)
`onClickBlocks` ( call the monitor to place the block on the canvas)
`removeBlock` (remove the block from the list)
`addBlock` (add blocks to the list)

### DropDownPaletteModel

`categoryNameList = []` (List of advance category blocks)
`AdvanceBlockList = []` (block corresponding to advance category)
`selectedCategroy` (the selected category)

### DropDownPaletteController

`renderCategory` (render the categories is each block list)
`renderBlocks` (call the monitor to return the data of advance blocks)
 
### Some function that is required from other components/files

`getIconsSVG` (the SVG of the section icons music, logic, art)
`getButtonsSVG` (the SVG of the button's icon)
`getBlockData` (the data of the blocks to be rendered)
`addBlockToCanvas` 
`getBlocks` (return the blocks the render them in the menu)

**Comment by meganindya** [comment]
Think of it as a hierarchy of two components. On top you have the Palette main component, which handles the position and visibility of the entire palette and contains the selector buttons for the different categories (3 as of now — music, logic, art). Then you have a sub-component similar to what you are calling the `BlockPalette`. This handles the visibility of and interaction with the blocks of the selected category.

**Comment by joykirat18** [comment]
I think the diagram is creating some confusing,  all the three components(music, logic, art) will be part of the `buttonPalette`, only the model will change. We will just define the 3 section in the `sectionName` list in `PaletteModel` and their corresponding buttons in `buttonNames` in `buttonPaletteModel`. And the controller will provide the data to their corresponding views.

**Comment by walterbender** [comment]
Have you thought about how low shelf/high shelf wil work?

**Comment by joykirat18** [comment]
Currently I am a bit confused how we will represent the low self and high self palette. Will we be adding more categories along music, art and logic or there will be subCategories inside these. I think if we want to simple add more categories along the existing 3 we will only want to change the sectionName list in paletteModel. But the other approach of adding subCategories might require some changes in the existing structure.

**Comment by meganindya** [comment]
Please create a checklist of the objectives you've listed. You could create a new branch and place items according to the expected project structure from your prototype branch and create a PR, rather than trying to modify that.

**Comment by meganindya** [comment]
completed in #95.
