### ISSUE TITLE
Artboard Framework

### ISSUE THREAD

**Issue by b18050** [sugarlabs/musicblocks-v4#58]
Canvas MVC structure

Canvas is associated with turtles, blocks, palette, toolbar, trashcan, pasteBox, etc.

### Model

Stores all the state and data required by the components.
<ul> 
<li> width - stores the width of the canvas</li>
<li> height - stores the height of the canvas </li>
<li> backGroundColor - stores the bkackground color </li>
<li> isVisible - stores the boolean if canas is visible</li>
<li> canvasColor - color of the canvas</li>
<li> canvasAlpha (turtles) </li>
<li> offsetLeft </li>
<li> offsetTop </li>

</ul>

### Controller

The controller will fetch the data from the model and render the results using the View. It also communicates
with the monitor of MusicBlock, which provides and fetches data to/from other controllers.

<ul>
<li> clearCanvas - clears everything on the canvas (bitmap, blocks, </li>
<li> refreshCanvas - refresh the canvas based on some changes (it can be used as a call back function)</li>
<li> isCanvasBlank - compares existing canvas with a new blank canvas and returns a boolean </li> 
<li> setCanvas - set the canvas based on argument passed (association with trashcan, turtles,blocks,palettes,pasteBox).</li>
<li> isCanvasOnTop</li>
<li> moveCanvasToTop</li>
<li> zoomIn</li>
<li> zoomOut</li>
<li> addToCanvas</li>
</ul>

**Comment by meganindya** [comment]
Toggling layer visibility could be an interesting behaviour.

**Comment by b18050** [comment]
![image](https://user-images.githubusercontent.com/45814442/123537788-df608e00-d74e-11eb-8702-7674b0db84a5.png)
![image](https://user-images.githubusercontent.com/45814442/123537953-d7edb480-d74f-11eb-8745-64fb1358f76b.png)
![image](https://user-images.githubusercontent.com/45814442/123538922-b3e0a200-d754-11eb-988e-df51620d5353.png)
Thanks @meganindya.

**Comment by meganindya** [comment]
completed in #95.
