### ISSUE TITLE
i18n Framework

### ISSUE THREAD

**Issue by walterbender** [sugarlabs/musicblocks-v4#66]
**ON  HOLD**

<hr/>

We'd like to have a new framework for our internationalize our code. There are several problems with the i18n package used with Music Blocks 3:

* there is no support for plurals or other common syntax, requiring lots of excepts being added to the code;
* the localization.ini file is huge and continues to grow since all of the languages are bundled into one file;
* the package is not actively maintained.

https://github.com/formatjs/formatjs looks like a good candidate: well maintained; under an MIT license.

**Comment by meganindya** [comment]
I did a reading of the FormatJS website. Looks like it supports _React_ and _TypeScript_ out of the box. Would be need to build a wrapper?

**Comment by meganindya** [comment]
@liamnorm I think you could start with a little case study of where and how localisation is used the Music Blocks v3. I think that should give you an idea of the exact objectives.

**Comment by liamnorm** [comment]
I think I've gained a good understanding of how L10n works in Music Blocks 3. I searched around MB3, and what I see matches this workflow diagram from FormatJS. 

<img width="812" alt="workflow" src="https://user-images.githubusercontent.com/56448763/123887182-07065080-d91f-11eb-907b-08d29d00b7a0.png">

FormatJS will work for our needs. It formats better and each language will have its own .json in a lang directory.
I don't know what exactly a wrapper would entail, but from what I see, we will need a script somewhere to initialize our own intl object with the strings we want. [The examples I found](https://github.com/formatjs/formatjs/blob/main/packages/react-intl/examples/HandleChange.tsx) call from a React app and show how to support changing language without refreshing. There is a lot of unfamiliar tsx stuff i'm trying to follow along with but I think it can be implemented pretty simply in our main React app.

**Comment by walterbender** [comment]
I can help with generation of the JSON files from the existing PO files. I also have scipts to scrape JS code to find strings for translation. All of this would need to be tweaked for the TS code base.

**Comment by walterbender** [comment]
JS to POT

[js2pot.zip](https://github.com/sugarlabs/musicblocks-v4/files/6776829/js2pot.zip)

**Comment by meganindya** [comment]
completed in #222
