### ISSUE TITLE
Decide on a License

### ISSUE THREAD

**Issue by meganindya** [sugarlabs/musicblocks-v4#67]
Need a distribution license for the app.

Possible candidate — [GNU Lesser General Public License (LGPL)](https://www.gnu.org/licenses/lgpl-3.0.html)

**Comment by meganindya** [comment]
@walterbender we need to decide on this ASAP.

**Comment by walterbender** [comment]
AGPL we can use another license if we need to

**Comment by meganindya** [comment]
AGPL v3.0 is already added.
