### ISSUE TITLE
Props artboard require from the manager

### ISSUE THREAD

**Issue by joykirat18** [sugarlabs/musicblocks-v4#83]
Currently there are 2 files `ArtBoardSketch.tsx` and `ArtBoardTurtle.tsx` in the view of artBoard. These 2 files are responsible for making the turtle and drawing on the canvas. The manager is required to call these 2 files to create multiple canvases and their corresponding turtles.

## Structure of canvas
If the program requires creating n canvases, then the manager should call create a list of n ArtBoard objects. Each object in the list should have a unique id and a unique turtle. 
We need to iterate over this Artboard list and call `ArtBoardSketch.tsx` n times. Props required: Turtle corresponding to each ArtBoard.

Manager should also maintain a list of all the turtles with their own unique id, this list should match the ArtBoard list. For example, any insertion/deletion of any artboard in the list should also reflect in the turtle list.
This turtle list should be passed as a prop to `ArtBoardTurtle.tsx`. All the n turtles will be on the topmost canvas on a single canvas. Therefore to create n canvases we will require n artBoardSketch and 1 ArtBoardTurtle.

**Comment by meganindya** [comment]
components refactored.
